service_account: default
users:
- name: making
  email: tmaki@vmware.com
  clusterroles:
  - app-editor
  - edit
- name: boltKrank
  email: simon.anderson111@gmail.com
  clusterroles:
  - app-editor
  - edit
- name: kayleema
  email: kmann@pivotal.io
  clusterroles:
  - app-editor
  - edit
